// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2y4GN54wkAmREnusOZtBv4HEZblNAZwA',
    appId: '1:65942792368:web:1b37e0ee8860ed42d77375',
    messagingSenderId: '65942792368',
    projectId: 'acomerlapp-5dbbb',
    authDomain: 'acomerlapp-5dbbb.firebaseapp.com',
    storageBucket: 'acomerlapp-5dbbb.appspot.com',
    measurementId: 'G-DL6M6ZJZFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHpHBEvQGNYCuQ7opBfAKrtOt3DH6o7aE',
    appId: '1:65942792368:android:f89d33012554397ad77375',
    messagingSenderId: '65942792368',
    projectId: 'acomerlapp-5dbbb',
    storageBucket: 'acomerlapp-5dbbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhYZo7_IKASkbVQadVXCPYDMiEpwiuZGc',
    appId: '1:65942792368:ios:1c7bcd6dae962054d77375',
    messagingSenderId: '65942792368',
    projectId: 'acomerlapp-5dbbb',
    storageBucket: 'acomerlapp-5dbbb.appspot.com',
    iosClientId: '65942792368-r38oc0gsrsdmqrm25m4k15ahtvshl0ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.acomerlapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhYZo7_IKASkbVQadVXCPYDMiEpwiuZGc',
    appId: '1:65942792368:ios:c80bf85dd1093cb6d77375',
    messagingSenderId: '65942792368',
    projectId: 'acomerlapp-5dbbb',
    storageBucket: 'acomerlapp-5dbbb.appspot.com',
    iosClientId: '65942792368-bv0b11tv6ieum4djra2c585fkjvrl2ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.acomerlapp.RunnerTests',
  );
}
